In [0]:
data=[["Raghul",38],["Bala",40],["Madhavan",45],["Malini",31]]

In [0]:
df=spark.sparkContext.parallelize(data).toDF(["Name","Age"])
df.show()

+--------+---+
|    Name|Age|
+--------+---+
|  Raghul| 38|
|    Bala| 40|
|Madhavan| 45|
|  Malini| 31|
+--------+---+

In [0]:
df.write.format("delta").mode("append").option("mergeSchema",True).saveAsTable("Customer")

In [0]:
spark.sql("SELECT * FROM Customer").show()

+--------+---+
|    Name|Age|
+--------+---+
|Madhavan| 45|
|  Raghul| 38|
|  Malini| 31|
|    Bala| 40|
+--------+---+

In [0]:
data1=[["Ramesh",38,"BE"],["Levin",40,"MCA"],["Saraswathi",45,"ME"],["Satya",31,"BSc"]]
rdd1=spark.sparkContext.parallelize(data1)
df1=rdd1.toDF(["Name","Age","Education"])
df1.show()

+----------+---+---------+
|      Name|Age|Education|
+----------+---+---------+
|    Ramesh| 38|       BE|
|     Levin| 40|      MCA|
|Saraswathi| 45|       ME|
|     Satya| 31|      BSc|
+----------+---+---------+

In [0]:
df1.write.format("delta").mode("append").option("mergeSchema",True).saveAsTable("Customer")

In [0]:
spark.sql("SELECT * FROM Customer").show()

+----------+---+---------+
|      Name|Age|Education|
+----------+---+---------+
|Saraswathi| 45|       ME|
|     Levin| 40|      MCA|
|     Satya| 31|      BSc|
|    Ramesh| 38|       BE|
|  Madhavan| 45|     null|
|    Raghul| 38|     null|
|    Malini| 31|     null|
|      Bala| 40|     null|
+----------+---+---------+